# Generated by Django 4.1.3 on 2023-03-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('malignant_case', models.IntegerField(default=0)),
                ('benign_case', models.IntegerField(default=0)),
                ('normal_case', models.IntegerField(default=0)),
                ('suggested_medicines', models.ManyToManyField(blank=True, to='app1.medicine')),
            ],
        ),
    ]
